# Generated by Django 4.2.23 on 2025-09-03 08:14

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app, Example"),
                    ("manage_access", "Can manage Example"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
