/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/example/api/example/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Example
         * @description Get Example Data
         *
         *     This endpoint retrieves example data for the authenticated user.
         *
         *     Returns:
         *         200: Example data retrieved successfully.
         *         403: Permission Denied.
         */
        get: operations["example_api_character_get_example"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/example/api/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Killstats navigation menu */
        get: operations["example_api_general_get_menu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/example/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["example_api_general_get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/example/api/modify/user/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modify User Settings */
        post: operations["example_api_general_modify_user_settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ExampleSchema */
        ExampleSchema: {
            /** Character Id */
            character_id?: number | null;
            /** Character Name */
            character_name?: string | null;
            /** Corporation Id */
            corporation_id?: number | null;
            /** Corporation Name */
            corporation_name?: string | null;
        };
        /**
         * MenuLink
         * @description Represents a link in the menu.
         *
         *     Parameters:
         *         name (str): The name of the menu link.
         *         link (str | None): The URL or path the menu link points to.
         *         is_external (bool): Indicates if the link is an external link.
         */
        MenuLink: {
            /** Name */
            name: string;
            /** Link */
            link?: string;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
        };
        /**
         * MenuModalSchema
         * @description Schema for menu modals, including the example modal.
         */
        MenuModalSchema: {
            create_example?: components["schemas"]["ModalSchema"] | null;
        };
        /**
         * MenuSchema
         * @description Schema for the overall menu, including links and modals.
         *
         *     Parameters:
         *         links (list[MenuLink]): The list of links in the menu.
         *         modals (MenuModalSchema | None): The modals associated with the menu.
         */
        MenuSchema: {
            /**
             * Left Links
             * @default []
             */
            left_links: components["schemas"]["MenuLink"][];
            /**
             * Right Links
             * @default []
             */
            right_links: components["schemas"]["MenuLink"][];
            modals?: components["schemas"]["MenuModalSchema"] | null;
        };
        /**
         * ModalSchema
         * @description Schema for modal dialog data.
         */
        ModalSchema: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Icon */
            icon: string;
            /** Modal Id */
            modal_id: string;
            /** Url */
            url: string;
            /** Color */
            color?: string | null;
            /** Buttontext */
            buttonText?: string | null;
        };
        /**
         * UserData
         * @description Schema for user data, including character ID and character name.
         *
         *     Parameters:
         *         user_id (int): The ID of the user.
         *         character_id (int): The ID of the character associated with the user.
         *         character_name (str): The name of the character.
         *         corporation_id (int): The ID of the corporation associated with the user.
         *         corporation_name (str): The name of the corporation associated with the user.
         *         alliance_id (int | None): The ID of the alliance associated with the user, if any.
         *         alliance_name (str | None): The name of the alliance associated with the user, if any.
         *         portrait (str | None): The URL or path to the character's portrait image.
         *         is_admin (boolean): The admin status for the user.
         *         notification (boolean): The notification status for the user.
         */
        UserData: {
            /** User Id */
            user_id: number;
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /** Alliance Id */
            alliance_id?: number | null;
            /** Alliance Name */
            alliance_name?: string | null;
            /** Portrait */
            portrait?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /** Notification */
            notification: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    example_api_character_get_example: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    example_api_general_get_menu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
        };
    };
    example_api_general_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    example_api_general_modify_user_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
